spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Wang223366!
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  config: classpath:logback.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.ruibin.pojo

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

comment.avatar: /images/yellow.png
message.avatar: /images/yellow.png